imagePullSecrets:
  - name: ocpregcred

imageCredentials:
  registry: image-registry.openshift-image-registry.svc:5000
  username: developer
  password: sha256~am8omh-0SBvn0PuAddMR-j-oqtQT6tjws3RXzg060SQ

appName: fastapi-quickstart

imageName: fastapi-quickstart-app
tag: '1.4'

ports:
  port: 8000
  targetPort: 8000

namespace: ocp-fastapi-quickstart-project
